### ISSUE TITLE
Sending attestation document from enclave to parent instance

### ISSUE THREAD

**Issue by nitish-at** [brave-experiments/ia2#2]
Thank you @NullHypothesis for a clear explanation of how to interact with NSM API.
 I would like to confirm a few more things from this.
In the explanation for getting attestation document mentioned [here](https://github.com/brave-experiments/ia2/blob/master/doc/architecture.md#attestation),

1. Does the returned attestation document reside inside the enclave or Parent instance ?

2. It is documented that only from inside of an Enclave can a  request to attestation document can be called. In such case where we run a program inside an enclave which interacts with NSM API to get an attestation document, how can we send this attestation document to parent instance ?

**Comment by NullHypothesis** [comment]
> Does the returned attestation document reside inside the enclave or Parent instance ?

Depends on what you mean by "reside." The client requests the document, the enclave creates it, and the parent instance forwards it back to the client. The parent instance never sees the document in plain text but it could request its own attestation document.

> It is documented that only from inside of an Enclave can a request to attestation document can be called. In such case where we run a program inside an enclave which interacts with NSM API to get an attestation document, how can we send this attestation document to parent instance ?

The only way for the enclave to talk to the parent instance is via the VSOCK interface:
https://docs.aws.amazon.com/enclaves/latest/user/nitro-enclave-concepts.html#term-socket

There are various ways of implementing that. This repository uses a Web server that's bound to a VSOCK address:
https://github.com/brave-experiments/nitro-enclave-utils/blob/master/enclave.go#L125

Also, I'm closing this issue because it doesn't seem to be an issue with this code base.

**Comment by nitish-at** [comment]
Thank you for the explanation.
